# -*- coding: UTF-8 -*-
import os
from config import PATHS

input_path = PATHS['input_path']
output_path = PATHS['output_path']

def getGDBs():
    dirlist = os.listdir(input_path)

    gdblist = []
    for dir in dirlist:
        extension = os.path.splitext(dir)[1]

    if ".gdb" in dir: #如果路径名称中包含 .gdb 字符串
        gdblist.append(input_path+"\\"+dir) #将GDB数据库的路径添加到gdblist列表中

    return gdblist

admin_codes = [
{ 'City' :  u'成都市', 'County' : u'锦江区', 'CountyCode' : '510104' },
{ 'City' :  u'成都市', 'County' : u'青羊区', 'CountyCode' : '510105'},
{ 'City' :  u'成都市', 'County' : u'金牛区', 'CountyCode' : '510106' },
{ 'City' :  u'成都市', 'County' : u'武侯区', 'CountyCode' : '510107' },
{ 'City' :  u'成都市', 'County' : u'成华区', 'CountyCode' : '510108' },
{ 'City' :  u'成都市', 'County' : u'高新区', 'CountyCode' : '510109' },
{ 'City' :  u'成都市', 'County' : u'天府新区成都直管区', 'CountyCode' : '510110'  },
{ 'City' :  u'成都市', 'County' : u'龙泉驿区', 'CountyCode' : '510112'  },
{ 'City' :  u'成都市', 'County' : u'青白江区', 'CountyCode' : '510113'  },
{ 'City' :  u'成都市', 'County' : u'新都区', 'CountyCode' : '510114'  },
{ 'City' :  u'成都市', 'County' : u'温江区', 'CountyCode' : '510115' },
{ 'City' :  u'成都市', 'County' : u'双流区', 'CountyCode' : '510116' },
{ 'City' :  u'成都市', 'County' : u'郫都区', 'CountyCode' : '510117'  },
{ 'City' :  u'成都市', 'County' : u'金堂县', 'CountyCode' : '510121'  },
{ 'City' :  u'成都市', 'County' : u'大邑县', 'CountyCode' : '510129' },
{ 'City' :  u'成都市', 'County' : u'蒲江县', 'CountyCode' : '510131'  },
{ 'City' :  u'成都市', 'County' : u'新津县', 'CountyCode' : '510118'  },
{ 'City' :  u'成都市', 'County' : u'都江堰市', 'CountyCode' : '510181'  },
{ 'City' :  u'成都市', 'County' : u'彭州市', 'CountyCode' : '510182'  },
{ 'City' :  u'成都市', 'County' : u'邛崃市', 'CountyCode' : '510183' },
{ 'City' :  u'成都市', 'County' : u'崇州市', 'CountyCode' : '510184'  },
{ 'City' :  u'成都市', 'County' : u'简阳市', 'CountyCode' : '510185'  },

{ 'City' :  u'自贡市', 'County' : u'自流井区', 'CountyCode' : '510302' },
{ 'City' :  u'自贡市', 'County' : u'贡井区', 'CountyCode' : '510303'  },
{ 'City' :  u'自贡市', 'County' : u'大安区', 'CountyCode' : '510304' },
{ 'City' :  u'自贡市', 'County' : u'沿滩区', 'CountyCode' : '510311' },
{ 'City' :  u'自贡市', 'County' : u'荣县', 'CountyCode' : '510321' },
{ 'City' :  u'自贡市', 'County' : u'富顺县', 'CountyCode' : '510322' },

{ 'City' :  u'攀枝花市', 'County' : u'东区', 'CountyCode' : '510402'},
{ 'City' :  u'攀枝花市', 'County' : u'西区', 'CountyCode' : '510403'},
{ 'City' :  u'攀枝花市', 'County' : u'仁和区', 'CountyCode' : '510411' },
{ 'City' :  u'攀枝花市', 'County' : u'米易县', 'CountyCode' : '510421'},
{ 'City' :  u'攀枝花市', 'County' : u'盐边县', 'CountyCode' : '510422' },

{ 'City' :  u'泸州市', 'County' : u'江阳区', 'CountyCode' : '510502' },
{ 'City' :  u'泸州市', 'County' : u'纳溪区', 'CountyCode' : '510503' },
{ 'City' :  u'泸州市', 'County' : u'龙马潭区', 'CountyCode' : '510504'},
{ 'City' :  u'泸州市', 'County' : u'泸县', 'CountyCode' : '510521' },
{ 'City' :  u'泸州市', 'County' : u'合江县', 'CountyCode' : '510522'},
{ 'City' :  u'泸州市', 'County' : u'叙永县', 'CountyCode' : '510524'},
{ 'City' :  u'泸州市', 'County' : u'古蔺县', 'CountyCode' : '510525'},

{ 'City' :  u'德阳市', 'County' : u'旌阳区', 'CountyCode' : '510603'},
{ 'City' :  u'德阳市', 'County' : u'罗江区', 'CountyCode' : '510604'},
{ 'City' :  u'德阳市', 'County' : u'中江县', 'CountyCode' : '510623'},
{ 'City' :  u'德阳市', 'County' : u'广汉市', 'CountyCode' : '510681'},
{ 'City' :  u'德阳市', 'County' : u'什邡市', 'CountyCode' : '510682'},
{ 'City' :  u'德阳市', 'County' : u'绵竹市', 'CountyCode' : '510683' },

{ 'City' :  u'绵阳市', 'County' : u'涪城区', 'CountyCode' : '510703'},
{ 'City' :  u'绵阳市', 'County' : u'游仙区', 'CountyCode' : '510704'},
{ 'City' :  u'绵阳市', 'County' : u'安州区', 'CountyCode' : '510705' },
{ 'City' :  u'绵阳市', 'County' : u'三台县', 'CountyCode' : '510722'},
{ 'City' :  u'绵阳市', 'County' : u'盐亭县', 'CountyCode' : '510723'},
{ 'City' :  u'绵阳市', 'County' : u'梓潼县', 'CountyCode' : '510725'},
{ 'City' :  u'绵阳市', 'County' : u'北川羌族自治县', 'CountyCode' : '510726' },
{ 'City' :  u'绵阳市', 'County' : u'平武县', 'CountyCode' : '510727' },
{ 'City' :  u'绵阳市', 'County' : u'江油市', 'CountyCode' : '510781'},

{ 'City' :  u'广元市', 'County' : u'利州区', 'CountyCode' : '510802' },
{ 'City' :  u'广元市', 'County' : u'昭化区', 'CountyCode' : '510811' },
{ 'City' :  u'广元市', 'County' : u'朝天区', 'CountyCode' : '510812'},
{ 'City' :  u'广元市', 'County' : u'旺苍县', 'CountyCode' : '510821'},
{ 'City' :  u'广元市', 'County' : u'青川县', 'CountyCode' : '510822'},
{ 'City' :  u'广元市', 'County' : u'剑阁县', 'CountyCode' : '510823'},
{ 'City' :  u'广元市', 'County' : u'苍溪县', 'CountyCode' : '510824'},

{ 'City' :  u'遂宁市', 'County' : u'船山区', 'CountyCode' : '510903' },
{ 'City' :  u'遂宁市', 'County' : u'安居区', 'CountyCode' : '510904'},
{ 'City' :  u'遂宁市', 'County' : u'蓬溪县', 'CountyCode' : '510921'},
{ 'City' :  u'遂宁市', 'County' : u'射洪县', 'CountyCode' : '510922'},
{ 'City' :  u'遂宁市', 'County' : u'大英县', 'CountyCode' : '510923'},

{ 'City' :  u'内江市', 'County' : u'市中区', 'CountyCode' : '511002'},
{ 'City' :  u'内江市', 'County' : u'东兴区', 'CountyCode' : '511011'},
{ 'City' :  u'内江市', 'County' : u'威远县', 'CountyCode' : '511024' },
{ 'City' :  u'内江市', 'County' : u'资中县', 'CountyCode' : '511025' },
{ 'City' :  u'内江市', 'County' : u'隆昌市', 'CountyCode' : '511083' },

{ 'City' :  u'乐山市', 'County' : u'市中区', 'CountyCode' : '511102'},
{ 'City' :  u'乐山市', 'County' : u'沙湾区', 'CountyCode' : '511111'},
{ 'City' :  u'乐山市', 'County' : u'五通桥区', 'CountyCode' : '511112'},
{ 'City' :  u'乐山市', 'County' : u'金口河区', 'CountyCode' : '511113'},
{ 'City' :  u'乐山市', 'County' : u'犍为县', 'CountyCode' : '511123' },
{ 'City' :  u'乐山市', 'County' : u'井研县', 'CountyCode' : '511124'  },
{ 'City' :  u'乐山市', 'County' : u'夹江县', 'CountyCode' : '511126'  },
{ 'City' :  u'乐山市', 'County' : u'沐川县', 'CountyCode' : '511129' },
{ 'City' :  u'乐山市', 'County' : u'峨边彝族自治县', 'CountyCode' : '511132' },
{ 'City' :  u'乐山市', 'County' : u'马边彝族自治县', 'CountyCode' : '511133'  },
{ 'City' :  u'乐山市', 'County' : u'峨眉山市', 'CountyCode' : '511181'},

{ 'City' :  u'南充市', 'County' : u'顺庆区', 'CountyCode' : '511302'  },
{ 'City' :  u'南充市', 'County' : u'高坪区', 'CountyCode' : '511303'  },
{ 'City' :  u'南充市', 'County' : u'嘉陵区', 'CountyCode' : '511304'  },
{ 'City' :  u'南充市', 'County' : u'南部县', 'CountyCode' : '511321' },
{ 'City' :  u'南充市', 'County' : u'营山县', 'CountyCode' : '511322' },
{ 'City' :  u'南充市', 'County' : u'蓬安县', 'CountyCode' : '511323'  },
{ 'City' :  u'南充市', 'County' : u'仪陇县', 'CountyCode' : '511324'  },
{ 'City' :  u'南充市', 'County' : u'西充县', 'CountyCode' : '511325'  },
{ 'City' :  u'南充市', 'County' : u'阆中市', 'CountyCode' : '511381'  },

{ 'City' :  u'眉山市', 'County' : u'东坡区', 'CountyCode' : '511402'  },
{ 'City' :  u'眉山市', 'County' : u'仁寿县', 'CountyCode' : '511421'  },
{ 'City' :  u'眉山市', 'County' : u'彭山区', 'CountyCode' : '511403'  },
{ 'City' :  u'眉山市', 'County' : u'洪雅县', 'CountyCode' : '511423' },
{ 'City' :  u'眉山市', 'County' : u'丹棱县', 'CountyCode' : '511424' },
{ 'City' :  u'眉山市', 'County' : u'青神县', 'CountyCode' : '511425'  },

{ 'City' :  u'宜宾市', 'County' : u'翠屏区', 'CountyCode' : '511502'  },
{ 'City' :  u'宜宾市', 'County' : u'叙州区', 'CountyCode' : '511504'  },
{ 'City' :  u'宜宾市', 'County' : u'南溪区', 'CountyCode' : '511503'  },
{ 'City' :  u'宜宾市', 'County' : u'江安县', 'CountyCode' : '511523' },
{ 'City' :  u'宜宾市', 'County' : u'长宁县', 'CountyCode' : '511524' },
{ 'City' :  u'宜宾市', 'County' : u'高县', 'CountyCode' : '511525' },
{ 'City' :  u'宜宾市', 'County' : u'珙县', 'CountyCode' : '511526' },
{ 'City' :  u'宜宾市', 'County' : u'筠连县', 'CountyCode' : '511527' },
{ 'City' :  u'宜宾市', 'County' : u'兴文县', 'CountyCode' : '511528' },
{ 'City' :  u'宜宾市', 'County' : u'屏山县', 'CountyCode' : '511529'  },

{ 'City' :  u'广安市', 'County' : u'广安区', 'CountyCode' : '511602' },
{ 'City' :  u'广安市', 'County' : u'前锋区', 'CountyCode' : '511603'  },
{ 'City' :  u'广安市', 'County' : u'岳池县', 'CountyCode' : '511621'  },
{ 'City' :  u'广安市', 'County' : u'武胜县', 'CountyCode' : '511622'  },
{ 'City' :  u'广安市', 'County' : u'邻水县', 'CountyCode' : '511623'  },
{ 'City' :  u'广安市', 'County' : u'华蓥市', 'CountyCode' : '511681'  },

{ 'City' :  u'达州市', 'County' : u'通川区', 'CountyCode' : '511702' },
{ 'City' :  u'达州市', 'County' : u'达川区', 'CountyCode' : '511703' },
{ 'City' :  u'达州市', 'County' : u'宣汉县', 'CountyCode' : '511722' },
{ 'City' :  u'达州市', 'County' : u'开江县', 'CountyCode' : '511723'  },
{ 'City' :  u'达州市', 'County' : u'大竹县', 'CountyCode' : '511724' },
{ 'City' :  u'达州市', 'County' : u'渠县', 'CountyCode' : '511725' },
{ 'City' :  u'达州市', 'County' : u'万源市', 'CountyCode' : '511781' },

{ 'City' :  u'雅安市', 'County' : u'雨城区', 'CountyCode' : '511802'},
{ 'City' :  u'雅安市', 'County' : u'名山区', 'CountyCode' : '511803' },
{ 'City' :  u'雅安市', 'County' : u'荥经县', 'CountyCode' : '511822'},
{ 'City' :  u'雅安市', 'County' : u'汉源县', 'CountyCode' : '511823' },
{ 'City' :  u'雅安市', 'County' : u'石棉县', 'CountyCode' : '511824'},
{ 'City' :  u'雅安市', 'County' : u'天全县', 'CountyCode' : '511825'},
{ 'City' :  u'雅安市', 'County' : u'芦山县', 'CountyCode' : '511826' },
{ 'City' :  u'雅安市', 'County' : u'宝兴县', 'CountyCode' : '511827' },

{ 'City' :  u'巴中市', 'County' : u'巴州区', 'CountyCode' : '511902' },
{ 'City' :  u'巴中市', 'County' : u'恩阳区', 'CountyCode' : '511903' },
{ 'City' :  u'巴中市', 'County' : u'通江县', 'CountyCode' : '511921' },
{ 'City' :  u'巴中市', 'County' : u'南江县', 'CountyCode' : '511922' },
{ 'City' :  u'巴中市', 'County' : u'平昌县', 'CountyCode' : '511923' },

{ 'City' :  u'资阳市', 'County' : u'雁江区', 'CountyCode' : '512002'  },
{ 'City' :  u'资阳市', 'County' : u'安岳县', 'CountyCode' : '512021'  },
{ 'City' :  u'资阳市', 'County' : u'乐至县', 'CountyCode' : '512022' },

{ 'City' :  u'阿坝藏族羌族自治州', 'County' : u'马尔康市', 'CountyCode' : '513201'},
{ 'City' :  u'阿坝藏族羌族自治州', 'County' : u'汶川县', 'CountyCode' : '513221' },
{ 'City' :  u'阿坝藏族羌族自治州', 'County' : u'理县', 'CountyCode' : '513222' },
{ 'City' :  u'阿坝藏族羌族自治州', 'County' : u'茂县', 'CountyCode' : '513223' },
{ 'City' :  u'阿坝藏族羌族自治州', 'County' : u'松潘县', 'CountyCode' : '513224'  },
{ 'City' :  u'阿坝藏族羌族自治州', 'County' : u'九寨沟县', 'CountyCode' : '513225' },
{ 'City' :  u'阿坝藏族羌族自治州', 'County' : u'金川县', 'CountyCode' : '513226' },
{ 'City' :  u'阿坝藏族羌族自治州', 'County' : u'小金县', 'CountyCode' : '513227' },
{ 'City' :  u'阿坝藏族羌族自治州', 'County' : u'黑水县', 'CountyCode' : '513228' },
{ 'City' :  u'阿坝藏族羌族自治州', 'County' : u'壤塘县', 'CountyCode' : '513230' },
{ 'City' :  u'阿坝藏族羌族自治州', 'County' : u'阿坝县', 'CountyCode' : '513231' },
{ 'City' :  u'阿坝藏族羌族自治州', 'County' : u'若尔盖县', 'CountyCode' : '513232' },
{ 'City' :  u'阿坝藏族羌族自治州', 'County' : u'红原县', 'CountyCode' : '513233' },

{ 'City' :  u'甘孜藏族自治州', 'County' : u'康定市', 'CountyCode' : '513301' },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'泸定县', 'CountyCode' : '513322' },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'丹巴县', 'CountyCode' : '513323'},
{ 'City' :  u'甘孜藏族自治州', 'County' : u'九龙县', 'CountyCode' : '513324' },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'雅江县', 'CountyCode' : '513325' },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'道孚县', 'CountyCode' : '513326' },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'炉霍县', 'CountyCode' : '513327'},
{ 'City' :  u'甘孜藏族自治州', 'County' : u'甘孜县', 'CountyCode' : '513328' },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'新龙县', 'CountyCode' : '513329'  },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'德格县', 'CountyCode' : '513330' },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'白玉县', 'CountyCode' : '513331'  },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'石渠县', 'CountyCode' : '513332'  },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'色达县', 'CountyCode' : '513333'  },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'理塘县', 'CountyCode' : '513334'  },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'巴塘县', 'CountyCode' : '513335'  },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'乡城县', 'CountyCode' : '513336'  },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'稻城县', 'CountyCode' : '513337' },
{ 'City' :  u'甘孜藏族自治州', 'County' : u'得荣县', 'CountyCode' : '513338' },

{ 'City' :  u'凉山彝族自治州', 'County' : u'西昌市', 'CountyCode' : '513401' },
{ 'City' :  u'凉山彝族自治州', 'County' : u'木里藏族自治县', 'CountyCode' : '513422' },
{ 'City' :  u'凉山彝族自治州', 'County' : u'盐源县', 'CountyCode' : '513423' },
{ 'City' :  u'凉山彝族自治州', 'County' : u'德昌县', 'CountyCode' : '513424' },
{ 'City' :  u'凉山彝族自治州', 'County' : u'会理县', 'CountyCode' : '513425'},
{ 'City' :  u'凉山彝族自治州', 'County' : u'会东县', 'CountyCode' : '513426'},
{ 'City' :  u'凉山彝族自治州', 'County' : u'宁南县', 'CountyCode' : '513427' },
{ 'City' :  u'凉山彝族自治州', 'County' : u'普格县', 'CountyCode' : '513428'},
{ 'City' :  u'凉山彝族自治州', 'County' : u'布拖县', 'CountyCode' : '513429' },
{ 'City' :  u'凉山彝族自治州', 'County' : u'金阳县', 'CountyCode' : '513430'},
{ 'City' :  u'凉山彝族自治州', 'County' : u'昭觉县', 'CountyCode' : '513431' },
{ 'City' :  u'凉山彝族自治州', 'County' : u'喜德县', 'CountyCode' : '513432' },
{ 'City' :  u'凉山彝族自治州', 'County' : u'冕宁县', 'CountyCode' : '513433' },
{ 'City' :  u'凉山彝族自治州', 'County' : u'越西县', 'CountyCode' : '513434' },
{ 'City' :  u'凉山彝族自治州', 'County' : u'甘洛县', 'CountyCode' : '513435'},
{ 'City' :  u'凉山彝族自治州', 'County' : u'美姑县', 'CountyCode' : '513436' },
{ 'City' :  u'凉山彝族自治州', 'County' : u'雷波县', 'CountyCode' : '513437' }
]


